### ISSUE TITLE
Ask HN / Show HN comments not loading

### ISSUE THREAD

**Issue by jrm2k6** [RubenVanEldik/hackerdaily-frontend#29]
Hi,
Thanks a lot of hackerdaily, I use it..daily!

I noticed for the last few days that comment threads not originating from an external article are not loading, for example https://hackerdaily.io/34211457/comments. It seems to show that there is an issue displaying the external site name. This commit could potentially be the issue https://github.com/RubenVanEldik/hackerdaily-frontend/commit/d340c0d227654df0619e7eadcd1cae975402017f.

I would troubleshoot more myself but I didn't see an easy way to run the backend locally and generate the required test data.
<img width="663" alt="Screen Shot 2023-01-02 at 9 37 53 AM" src="https://user-images.githubusercontent.com/1088099/210245766-f95f62c1-dacd-42e0-8432-252c4ece11a9.png">

Let me know if you need more info, and happy new year 🎉

**Comment by RubenVanEldik** [comment]
Hi Jeremy,

Thank you for pointing this out!

This issue was indeed created by https://github.com/RubenVanEldik/hackerdaily-frontend/commit/d340c0d227654df0619e7eadcd1cae975402017f. The bug only arises if you're not coming from the homepage, as in that case there is no preview of the story. I fixed the bug with https://github.com/RubenVanEldik/hackerdaily-frontend/commit/d340c0d227654df0619e7eadcd1cae975402017f.

Have a great 2023!!
